version: "2"
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    command: sh -c "sleep 20s ; python main.py"

  mysql:
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"